name: RoDTesting
version: '${project.version}'
main: me.rod.rodtesting.RoDTesting
api-version: 1.19
authors: [ 5RoD ]
description: GraveCORE for everything
website: https://gravemc.net
commands:
  heal:
    description: heals you
    permission: rodtestingcore.admin
  feed:
    description: feeds you
    permission: rodtestingcore.vip
  setspawn:
    description: set spawn point command
    permission: rodtestingcore.admin
  spawn:
    description: teleports you to the spawn
  gmc:
    description: sets your gamemode to creative
    permission: rodtestingcore.admin
  fly:
    description: enables flight