name: RoDTesting
version: '${project.version}'
main: me.rod.rodtesting.RoDTesting
api-version: 1.19
authors: [ 5RoD ]
description: GraveCORE for everything
website: https://gravemc.net
commands:
  heal:
    description: sex heals you
  feed:
    description: feeds you
  setspawn:
    description: set spawn point command
  spawn:
    description: teleports you to the spawn